name: country_catalog
version: 1.1.0
author: Roland Volskaya
homepage: github.com/volskaya/country_catalog.dart
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  json_annotation: ^4.0.1
  freezed_annotation: ^0.14.1

dev_dependencies:
  json_serializable: ^4.1.0
  build_runner: ^1.10.0
  freezed: ^0.14.1+1

dependency_overrides:
  freezed_annotation:
    path: /home/projects/forks/freezed/packages/freezed_annotation
  freezed:
    path: /home/projects/forks/freezed/packages/freezed
  mobx_codegen:
    path: /home/projects/forks/mobx.dart/mobx_codegen

flutter:
  generate: true
