name: country_catalog
version: 1.1.0
author: Roland Volskaya
homepage: github.com/volskaya/country_catalog.dart
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  json_annotation: ^4.1.0
  freezed_annotation: ^0.14.1

dev_dependencies:
  build_runner:
  json_serializable: ^5.0.0
  freezed: ^0.14.1+1

dependency_overrides:
  freezed_annotation:
    path: /home/projects/forks/freezed/packages/freezed_annotation
  freezed:
    path: /home/projects/forks/freezed/packages/freezed
  mobx_codegen:
    path: /home/projects/forks/mobx.dart/mobx_codegen

flutter:
  generate: true
  assets:
    - packages/country_catalog/flags/ad.png
    - packages/country_catalog/flags/ae.png
    - packages/country_catalog/flags/af.png
    - packages/country_catalog/flags/ag.png
    - packages/country_catalog/flags/ai.png
    - packages/country_catalog/flags/al.png
    - packages/country_catalog/flags/am.png
    - packages/country_catalog/flags/an.png
    - packages/country_catalog/flags/ao.png
    - packages/country_catalog/flags/aq.png
    - packages/country_catalog/flags/ar.png
    - packages/country_catalog/flags/as.png
    - packages/country_catalog/flags/at.png
    - packages/country_catalog/flags/au.png
    - packages/country_catalog/flags/aw.png
    - packages/country_catalog/flags/ax.png
    - packages/country_catalog/flags/az.png
    - packages/country_catalog/flags/ba.png
    - packages/country_catalog/flags/bb.png
    - packages/country_catalog/flags/bd.png
    - packages/country_catalog/flags/be.png
    - packages/country_catalog/flags/bf.png
    - packages/country_catalog/flags/bg.png
    - packages/country_catalog/flags/bh.png
    - packages/country_catalog/flags/bi.png
    - packages/country_catalog/flags/bj.png
    - packages/country_catalog/flags/bl.png
    - packages/country_catalog/flags/bm.png
    - packages/country_catalog/flags/bn.png
    - packages/country_catalog/flags/bo.png
    - packages/country_catalog/flags/bq.png
    - packages/country_catalog/flags/br.png
    - packages/country_catalog/flags/bs.png
    - packages/country_catalog/flags/bt.png
    - packages/country_catalog/flags/bv.png
    - packages/country_catalog/flags/bw.png
    - packages/country_catalog/flags/by.png
    - packages/country_catalog/flags/bz.png
    - packages/country_catalog/flags/ca.png
    - packages/country_catalog/flags/cc.png
    - packages/country_catalog/flags/cd.png
    - packages/country_catalog/flags/cf.png
    - packages/country_catalog/flags/cg.png
    - packages/country_catalog/flags/ch.png
    - packages/country_catalog/flags/ci.png
    - packages/country_catalog/flags/ck.png
    - packages/country_catalog/flags/cl.png
    - packages/country_catalog/flags/cm.png
    - packages/country_catalog/flags/cn.png
    - packages/country_catalog/flags/co.png
    - packages/country_catalog/flags/cr.png
    - packages/country_catalog/flags/cu.png
    - packages/country_catalog/flags/cv.png
    - packages/country_catalog/flags/cw.png
    - packages/country_catalog/flags/cx.png
    - packages/country_catalog/flags/cy.png
    - packages/country_catalog/flags/cz.png
    - packages/country_catalog/flags/de.png
    - packages/country_catalog/flags/dj.png
    - packages/country_catalog/flags/dk.png
    - packages/country_catalog/flags/dm.png
    - packages/country_catalog/flags/do.png
    - packages/country_catalog/flags/dz.png
    - packages/country_catalog/flags/ec.png
    - packages/country_catalog/flags/ee.png
    - packages/country_catalog/flags/eg.png
    - packages/country_catalog/flags/eh.png
    - packages/country_catalog/flags/er.png
    - packages/country_catalog/flags/es.png
    - packages/country_catalog/flags/et.png
    - packages/country_catalog/flags/eu.png
    - packages/country_catalog/flags/fi.png
    - packages/country_catalog/flags/fj.png
    - packages/country_catalog/flags/fk.png
    - packages/country_catalog/flags/fm.png
    - packages/country_catalog/flags/fo.png
    - packages/country_catalog/flags/fr.png
    - packages/country_catalog/flags/ga.png
    - packages/country_catalog/flags/gb-eng.png
    - packages/country_catalog/flags/gb-nir.png
    - packages/country_catalog/flags/gb.png
    - packages/country_catalog/flags/gb-sct.png
    - packages/country_catalog/flags/gb-wls.png
    - packages/country_catalog/flags/gd.png
    - packages/country_catalog/flags/ge.png
    - packages/country_catalog/flags/gf.png
    - packages/country_catalog/flags/gg.png
    - packages/country_catalog/flags/gh.png
    - packages/country_catalog/flags/gi.png
    - packages/country_catalog/flags/gl.png
    - packages/country_catalog/flags/gm.png
    - packages/country_catalog/flags/gn.png
    - packages/country_catalog/flags/gp.png
    - packages/country_catalog/flags/gq.png
    - packages/country_catalog/flags/gr.png
    - packages/country_catalog/flags/gs.png
    - packages/country_catalog/flags/gt.png
    - packages/country_catalog/flags/gu.png
    - packages/country_catalog/flags/gw.png
    - packages/country_catalog/flags/gy.png
    - packages/country_catalog/flags/hk.png
    - packages/country_catalog/flags/hm.png
    - packages/country_catalog/flags/hn.png
    - packages/country_catalog/flags/hr.png
    - packages/country_catalog/flags/ht.png
    - packages/country_catalog/flags/hu.png
    - packages/country_catalog/flags/id.png
    - packages/country_catalog/flags/ie.png
    - packages/country_catalog/flags/il.png
    - packages/country_catalog/flags/im.png
    - packages/country_catalog/flags/in.png
    - packages/country_catalog/flags/io.png
    - packages/country_catalog/flags/iq.png
    - packages/country_catalog/flags/ir.png
    - packages/country_catalog/flags/is.png
    - packages/country_catalog/flags/it.png
    - packages/country_catalog/flags/je.png
    - packages/country_catalog/flags/jm.png
    - packages/country_catalog/flags/jo.png
    - packages/country_catalog/flags/jp.png
    - packages/country_catalog/flags/ke.png
    - packages/country_catalog/flags/kg.png
    - packages/country_catalog/flags/kh.png
    - packages/country_catalog/flags/ki.png
    - packages/country_catalog/flags/km.png
    - packages/country_catalog/flags/kn.png
    - packages/country_catalog/flags/kp.png
    - packages/country_catalog/flags/kr.png
    - packages/country_catalog/flags/kw.png
    - packages/country_catalog/flags/ky.png
    - packages/country_catalog/flags/kz.png
    - packages/country_catalog/flags/la.png
    - packages/country_catalog/flags/lb.png
    - packages/country_catalog/flags/lc.png
    - packages/country_catalog/flags/li.png
    - packages/country_catalog/flags/lk.png
    - packages/country_catalog/flags/lr.png
    - packages/country_catalog/flags/ls.png
    - packages/country_catalog/flags/lt.png
    - packages/country_catalog/flags/lu.png
    - packages/country_catalog/flags/lv.png
    - packages/country_catalog/flags/ly.png
    - packages/country_catalog/flags/ma.png
    - packages/country_catalog/flags/mc.png
    - packages/country_catalog/flags/md.png
    - packages/country_catalog/flags/me.png
    - packages/country_catalog/flags/mf.png
    - packages/country_catalog/flags/mg.png
    - packages/country_catalog/flags/mh.png
    - packages/country_catalog/flags/mk.png
    - packages/country_catalog/flags/ml.png
    - packages/country_catalog/flags/mm.png
    - packages/country_catalog/flags/mn.png
    - packages/country_catalog/flags/mo.png
    - packages/country_catalog/flags/mp.png
    - packages/country_catalog/flags/mq.png
    - packages/country_catalog/flags/mr.png
    - packages/country_catalog/flags/ms.png
    - packages/country_catalog/flags/mt.png
    - packages/country_catalog/flags/mu.png
    - packages/country_catalog/flags/mv.png
    - packages/country_catalog/flags/mw.png
    - packages/country_catalog/flags/mx.png
    - packages/country_catalog/flags/my.png
    - packages/country_catalog/flags/mz.png
    - packages/country_catalog/flags/na.png
    - packages/country_catalog/flags/nc.png
    - packages/country_catalog/flags/ne.png
    - packages/country_catalog/flags/nf.png
    - packages/country_catalog/flags/ng.png
    - packages/country_catalog/flags/ni.png
    - packages/country_catalog/flags/nl.png
    - packages/country_catalog/flags/no.png
    - packages/country_catalog/flags/np.png
    - packages/country_catalog/flags/nr.png
    - packages/country_catalog/flags/nu.png
    - packages/country_catalog/flags/nz.png
    - packages/country_catalog/flags/om.png
    - packages/country_catalog/flags/pa.png
    - packages/country_catalog/flags/pe.png
    - packages/country_catalog/flags/pf.png
    - packages/country_catalog/flags/pg.png
    - packages/country_catalog/flags/ph.png
    - packages/country_catalog/flags/pk.png
    - packages/country_catalog/flags/pl.png
    - packages/country_catalog/flags/pm.png
    - packages/country_catalog/flags/pn.png
    - packages/country_catalog/flags/pr.png
    - packages/country_catalog/flags/ps.png
    - packages/country_catalog/flags/pt.png
    - packages/country_catalog/flags/pw.png
    - packages/country_catalog/flags/py.png
    - packages/country_catalog/flags/qa.png
    - packages/country_catalog/flags/re.png
    - packages/country_catalog/flags/ro.png
    - packages/country_catalog/flags/rs.png
    - packages/country_catalog/flags/ru.png
    - packages/country_catalog/flags/rw.png
    - packages/country_catalog/flags/sa.png
    - packages/country_catalog/flags/sb.png
    - packages/country_catalog/flags/sc.png
    - packages/country_catalog/flags/sd.png
    - packages/country_catalog/flags/se.png
    - packages/country_catalog/flags/sg.png
    - packages/country_catalog/flags/sh.png
    - packages/country_catalog/flags/si.png
    - packages/country_catalog/flags/sj.png
    - packages/country_catalog/flags/sk.png
    - packages/country_catalog/flags/sl.png
    - packages/country_catalog/flags/sm.png
    - packages/country_catalog/flags/sn.png
    - packages/country_catalog/flags/so.png
    - packages/country_catalog/flags/sr.png
    - packages/country_catalog/flags/ss.png
    - packages/country_catalog/flags/st.png
    - packages/country_catalog/flags/sv.png
    - packages/country_catalog/flags/sx.png
    - packages/country_catalog/flags/sy.png
    - packages/country_catalog/flags/sz.png
    - packages/country_catalog/flags/tc.png
    - packages/country_catalog/flags/td.png
    - packages/country_catalog/flags/tf.png
    - packages/country_catalog/flags/tg.png
    - packages/country_catalog/flags/th.png
    - packages/country_catalog/flags/tj.png
    - packages/country_catalog/flags/tk.png
    - packages/country_catalog/flags/tl.png
    - packages/country_catalog/flags/tm.png
    - packages/country_catalog/flags/tn.png
    - packages/country_catalog/flags/to.png
    - packages/country_catalog/flags/tr.png
    - packages/country_catalog/flags/tt.png
    - packages/country_catalog/flags/tv.png
    - packages/country_catalog/flags/tw.png
    - packages/country_catalog/flags/tz.png
    - packages/country_catalog/flags/ua.png
    - packages/country_catalog/flags/ug.png
    - packages/country_catalog/flags/um.png
    - packages/country_catalog/flags/us.png
    - packages/country_catalog/flags/uy.png
    - packages/country_catalog/flags/uz.png
    - packages/country_catalog/flags/va.png
    - packages/country_catalog/flags/vc.png
    - packages/country_catalog/flags/ve.png
    - packages/country_catalog/flags/vg.png
    - packages/country_catalog/flags/vi.png
    - packages/country_catalog/flags/vn.png
    - packages/country_catalog/flags/vu.png
    - packages/country_catalog/flags/wf.png
    - packages/country_catalog/flags/ws.png
    - packages/country_catalog/flags/xk.png
    - packages/country_catalog/flags/ye.png
    - packages/country_catalog/flags/yt.png
    - packages/country_catalog/flags/za.png
    - packages/country_catalog/flags/zm.png
    - packages/country_catalog/flags/zw.png
