name: country_catalog
version: 1.0.0
author: Roland Volskaya
homepage: github.com/volskaya/country_catalog.dart
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  json_annotation:
  freezed: ^0.12.6
  i69n: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable:
  build_runner: ^1.10.0
  freezed_annotation: ^0.12.0

dependency_overrides:
  analyzer: ^0.39.12
  intl_translation: ^0.17.10+1
  intl: 0.17.0
  freezed_annotation:
    path: /home/projects/forks/freezed/packages/freezed_annotation
  freezed:
    path: /home/projects/forks/freezed/packages/freezed
  mobx_codegen:
    path: /home/projects/forks/mobx.dart/mobx_codegen
